name: feather_note
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2  # 👈 เพิ่มตรงนี้
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^11.0.0
  pdf: ^3.10.4
  printing: ^5.12.0
  screenshot: ^3.0.0
  path_provider: ^2.0.15
  flutter_quill: ^11.4.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true